### PR TITLE
Revert "Lite obfuscation"

### PR DESCRIPTION
**Pull request by csh519**
Reverts Samsung/CredData#54

### CODE REVIEW

**Review by babenek — COMMENTED** [review]
The rollback requires undo for https://github.com/Samsung/CredSweeper/pull/459
Or just remove the argument --lite_obfuscation
https://github.com/Samsung/CredSweeper/blob/975fd20ceeb3a695e753f5b19365f16b06323da6/.github/workflows/benchmark.yml#L49

**Review by babenek — CHANGES_REQUESTED** [review]
The PR is not necessary. Moreover, it fails benchmark workflow. Just remove ``--lite_obfuscation``

**Comment by babenek** [comment]
https://github.com/Samsung/CredSweeper/pull/465 let remove the workflow enterelly to avoid a data leakage.

**Comment by csh519** [comment]
> The PR is not necessary. Moreover, it fails benchmark workflow. Just remove `--lite_obfuscation`

I agree with this. Let just remove `--lite_obfuscation` option. Not to remove the workflow of CredSweeper.
It's too much..

**Comment by csh519** [comment]
I created the PR #57 for remove `--lite_obfuscation` option only.
Please check.

**Pull request closed without merging**
