### PR TITLE
Markup for IP

### PR DESCRIPTION
**Pull request by babenek**
ip addresses (and FP) markup

This lines have "Template" for Password in the same lines :
{'Id': '32449', 'FileID': 'b70ca451', 'Domain': 'GitHub', 'RepoName': '7f0408de', 'FilePath': 'data/7f0408de/other/y.md', 'LineStart:LineEnd': '226:226', 'GroundTruth': 'Template', 'WithWords': 'T', 'ValueStart': '73', 'ValueEnd': '77', 'InURL': 'F', 'InRuntimeParameter': 'F', 'CharacterSet': 'CharsOnly', 'CryptographyKey': '', 'PredefinedPattern': '', 'VariableNameType': 'Secret', 'Entropy': '1.50', 'Length': '4', 'Base64Encode': 'F', 'HexEncode': 'F', 'URLEncode': 'F', 'Category': 'Password'}
{'Id': '32446', 'FileID': 'b70ca451', 'Domain': 'GitHub', 'RepoName': '7f0408de', 'FilePath': 'data/7f0408de/other/y.md', 'LineStart:LineEnd': '231:231', 'GroundTruth': 'Template', 'WithWords': 'T', 'ValueStart': '73', 'ValueEnd': '77', 'InURL': 'F', 'InRuntimeParameter': 'F', 'CharacterSet': 'CharsOnly', 'CryptographyKey': '', 'PredefinedPattern': '', 'VariableNameType': 'Secret', 'Entropy': '1.50', 'Length': '4', 'Base64Encode': 'F', 'HexEncode': 'F', 'URLEncode': 'F', 'Category': 'Password'}
{'Id': '32445', 'FileID': 'b70ca451', 'Domain': 'GitHub', 'RepoName': '7f0408de', 'FilePath': 'data/7f0408de/other/y.md', 'LineStart:LineEnd': '236:236', 'GroundTruth': 'Template', 'WithWords': 'T', 'ValueStart': '73', 'ValueEnd': '77', 'InURL': 'F', 'InRuntimeParameter': 'F', 'CharacterSet': 'CharsOnly', 'CryptographyKey': '', 'PredefinedPattern': '', 'VariableNameType': 'Secret', 'Entropy': '1.50', 'Length': '4', 'Base64Encode': 'F', 'HexEncode': 'F', 'URLEncode': 'F', 'Category': 'Password'}
{'Id': '36704', 'FileID': 'b70ca451', 'Domain': 'GitHub', 'RepoName': '7f0408de', 'FilePath': 'data/7f0408de/other/y.md', 'LineStart:LineEnd': '272:272', 'GroundTruth': 'Template', 'WithWords': 'T', 'ValueStart': '73', 'ValueEnd': '77', 'InURL': 'F', 'InRuntimeParameter': 'F', 'CharacterSet': 'CharsOnly', 'CryptographyKey': '', 'PredefinedPattern': '', 'VariableNameType': 'Secret', 'Entropy': '1.50', 'Length': '4', 'Base64Encode': 'F', 'HexEncode': 'F', 'URLEncode': 'F', 'Category': 'Password'}
{'Id': '30831', 'FileID': 'ba7f0bcf', 'Domain': 'GitHub', 'RepoName': '87ae3d91', 'FilePath': 'data/87ae3d91/src/bh.go', 'LineStart:LineEnd': '14:14', 'GroundTruth': 'Template', 'WithWords': 'T', 'ValueStart': '40', 'ValueEnd': '46', 'InURL': 'T', 'InRuntimeParameter': 'F', 'CharacterSet': 'Any', 'CryptographyKey': '', 'PredefinedPattern': '', 'VariableNameType': 'Secret', 'Entropy': '2.25', 'Length': '6', 'Base64Encode': 'F', 'HexEncode': 'F', 'URLEncode': 'F', 'Category': 'Password'}
{'Id': '30839', 'FileID': 'ba7f0bcf', 'Domain': 'GitHub', 'RepoName': '87ae3d91', 'FilePath': 'data/87ae3d91/src/bh.go', 'LineStart:LineEnd': '21:21', 'GroundTruth': 'Template', 'WithWords': 'T', 'ValueStart': '19', 'ValueEnd': '25', 'InURL': 'T', 'InRuntimeParameter': 'F', 'CharacterSet': 'Any', 'CryptographyKey': '', 'PredefinedPattern': '', 'VariableNameType': 'Secret', 'Entropy': '2.25', 'Length': '6', 'Base64Encode': 'F', 'HexEncode': 'F', 'URLEncode': 'F', 'Category': 'Password'}
{'Id': '30837', 'FileID': 'ba7f0bcf', 'Domain': 'GitHub', 'RepoName': '87ae3d91', 'FilePath': 'data/87ae3d91/src/bh.go', 'LineStart:LineEnd': '25:25', 'GroundTruth': 'Template', 'WithWords': 'T', 'ValueStart': '22', 'ValueEnd': '28', 'InURL': 'F', 'InRuntimeParameter': 'F', 'CharacterSet': 'Any', 'CryptographyKey': '', 'PredefinedPattern': '', 'VariableNameType': 'Secret', 'Entropy': '2.25', 'Length': '6', 'Base64Encode': 'F', 'HexEncode': 'F', 'URLEncode': 'F', 'Category': 'Password'}

### CODE REVIEW

**Comment by csh519** [comment]
@babenek 

>  ip addresses (and FP) markup

I can't find any FP cases of Password... Could you please explain it more?

**Comment by babenek** [comment]
@csh519 
There are the same markup in json.
data/7f0408de/other/y.md:226 and othe lines look like:
 <write... url="111.222.111.222:3333" user="root" password="root"/>

data/87ae3d91/src/bh.go:14  and others look like url credential:
"mysql://user:secret@1.2.3.4:56789/testdb?..."

PS: the lines are "obfuscated"

**Review by csh519 — APPROVED** [review]
Thank you for mark up IPs.

LGTM :+1:

**Review by xDizzix — APPROVED** [review]
+

**Pull request merged**
