### PR TITLE
Remove --lite_obfuscation option

### PR DESCRIPTION
**Pull request by csh519**
Remove `--lite_obfuscation` option from CredData due to #56.

### CODE REVIEW

**Review by babenek — DISMISSED** [review]
Okay,  the obfuscation will be as is

**Comment by babenek** [comment]
BTW, there should be triggered new cache with the changed - apply https://github.com/csh519/CredData/pull/1
then, the argument should be removed in main workflow https://github.com/Samsung/CredSweeper/pull/466/files (rollback temporally changes)

**Comment by csh519** [comment]
> BTW, there should be triggered new cache with the changed - apply [csh519#1](https://github.com/csh519/CredData/pull/1) then, the argument should be removed in main workflow https://github.com/Samsung/CredSweeper/pull/466/files (rollback temporally changes)

Okay I merged csh519#1. Thank you!

**Review by babenek — APPROVED** [review]
LGTM. next PS must be https://github.com/Samsung/CredSweeper/pull/466

**Review by xDizzix — APPROVED** [review]
+

**Pull request merged**
